# Generated by Django 6.1.1 on 2026-09-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=30)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencido', models.BooleanField(default=False)),
                ('acabou_antes_fim_mes', models.BooleanField(default=False)),
            ],
        ),
    ]
